//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cSharpVezba9V2.JavniServis {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="JavniServis.IJavniServis")]
    public interface IJavniServis {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJavniServis/ProsecneTemperature", ReplyAction="http://tempuri.org/IJavniServis/ProsecneTemperatureResponse")]
        double ProsecneTemperature(string stanica, System.DateTime pocetak, System.DateTime kraj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJavniServis/ProsecneTemperature", ReplyAction="http://tempuri.org/IJavniServis/ProsecneTemperatureResponse")]
        System.Threading.Tasks.Task<double> ProsecneTemperatureAsync(string stanica, System.DateTime pocetak, System.DateTime kraj);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IJavniServisChannel : cSharpVezba9V2.JavniServis.IJavniServis, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JavniServisClient : System.ServiceModel.ClientBase<cSharpVezba9V2.JavniServis.IJavniServis>, cSharpVezba9V2.JavniServis.IJavniServis {
        
        public JavniServisClient() {
        }
        
        public JavniServisClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JavniServisClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JavniServisClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JavniServisClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double ProsecneTemperature(string stanica, System.DateTime pocetak, System.DateTime kraj) {
            return base.Channel.ProsecneTemperature(stanica, pocetak, kraj);
        }
        
        public System.Threading.Tasks.Task<double> ProsecneTemperatureAsync(string stanica, System.DateTime pocetak, System.DateTime kraj) {
            return base.Channel.ProsecneTemperatureAsync(stanica, pocetak, kraj);
        }
    }
}
